contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    isoverridable: false
    itemVersion: 2.8.24
    packID: ServiceNow
    packName: ServiceNow
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    supportedModules:
    - X1
    - X3
    - X5
    - ENT_PLUS
    - asm
    - exposure_management
    - agentix
    - xsiam
    toServerVersion: ""
description: |
  Subplaybook for finding CI records in ServiceNow CMDB.
id: ServiceNow CMDB Search
inputs:
- description: The CMDB CI class to perform the search on (Defaults to cmdb_ci).
  key: SearchCIClass
  playbookInputQuery: null
  required: false
  value:
    simple: cmdb_ci
- description: The CI field used to perform the query (Defaults to ip_address).
  key: SearchQueryField
  playbookInputQuery: null
  required: false
  value:
    simple: ip_address
- description: The value used to perform the query.
  key: SearchQueryValue
  playbookInputQuery: null
  required: true
  value: {}
- description: Value to determine if the "add asset to CMDB" branch should be skipped
    in order to prevent direction to manual task.  By default this is set to "false"
    but a "true" value will bypass.
  key: BypassAddRecord
  playbookInputQuery: null
  required: false
  value:
    simple: "false"
name: ServiceNow CMDB Search
outlinetasks: {}
outputs:
- contextPath: ServiceNowCMDB.Record
  description: Discovered CI records
  type: unknown
- contextPath: ServiceNowCMDB.Records
  description: A list of all the records that were found in the CMDB table.
possibleresponses: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 95a33aa0-456c-4999-8d67-99c7e5559368
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 95a33aa0-456c-4999-8d67-99c7e5559368
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      class:
        simple: ${inputs.SearchCIClass}
      query:
        simple: ${inputs.SearchQueryField}=${inputs.SearchQueryValue}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow CMDB
      description: Query records for a CMDB class.
      id: d36ad1f6-c15d-47b5-878b-ee4a128b7ec1
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Search for CMDB record
      playbooktaskmissingcomponent: null
      script: ServiceNow CMDB|||servicenow-cmdb-records-list
      type: regular
      version: -1
    taskid: d36ad1f6-c15d-47b5-878b-ee4a128b7ec1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 920
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      class:
        simple: ${inputs.SearchCIClass}
      sys_id:
        complex:
          accessor: sys_id
          root: ServiceNowCMDB.Records
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow CMDB
      description: Query attributes and relationship information for a specific record.
      id: 3f33ff9e-9141-4a55-8cd4-c4be43ec194d
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Get record by ID
      playbooktaskmissingcomponent: null
      script: ServiceNow CMDB|||servicenow-cmdb-record-get-by-id
      type: regular
      version: -1
    taskid: 3f33ff9e-9141-4a55-8cd4-c4be43ec194d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1360
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      class:
        simple: cmdb_ci
      sys_id:
        complex:
          accessor: value
          root: ServiceNowCMDB.Record.Attributes.cmdb_ci
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow CMDB
      description: Query attributes and relationship information for a specific record.
      id: 47156e2a-4f91-4926-8b0b-a84bb3ea80b3
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Fetch related CMDB CI by ID
      playbooktaskmissingcomponent: null
      script: ServiceNow CMDB|||servicenow-cmdb-record-get-by-id
      type: regular
      version: -1
    taskid: 47156e2a-4f91-4926-8b0b-a84bb3ea80b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2040
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cde6d170-9365-4889-86f2-e6e3400626d0
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Playbook End
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: cde6d170-9365-4889-86f2-e6e3400626d0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1320,
          "y": 2530
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "15"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${ServiceNowCMDB.Records}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: d9396b1e-671e-4684-8177-8d10a6c2709d
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Do records exist?
      playbooktaskmissingcomponent: null
      script: Exists
      type: condition
      version: -1
    taskid: d9396b1e-671e-4684-8177-8d10a6c2709d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1090
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Do you want to add this asset in the CMDB?
      cc: null
      format: ""
      methods: []
      replyOptions:
      - "No"
      - "Yes"
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to:
        simple: Analyst
    nexttasks:
      "No":
      - "7"
      "Yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if you should add the asset into CMDB (manual task).
      id: 163630a4-45e6-40c9-84a5-2b9d9f4fe3a6
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Add asset in CMDB?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 163630a4-45e6-40c9-84a5-2b9d9f4fe3a6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1810
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: The asset is not in your CMDB, please manually add asset in ServiceNow
      id: f66dc3c1-9989-4920-8abc-ffc7ad432413
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Manually add asset in CMDB
      playbooktaskmissingcomponent: null
      type: regular
      version: -1
    taskid: f66dc3c1-9989-4920-8abc-ffc7ad432413
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 2040
        }
      }
  "13":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: CMDB Evidence
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      columns:
        simple: name,sys_class_name,sys_id,asset.display_value,asset.link,asset.value
      data:
        complex:
          accessor: Attributes}
          root: ${ServiceNowCMDB.Record
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Convert an array to a nice table display. Usually, from the context.
      id: 76fe59cd-cf7c-44a1-8f8b-7d4751fee3b2
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Save CMDB information in Evidence
      playbooktaskmissingcomponent: null
      script: ToTable
      type: regular
      version: -1
    taskid: 76fe59cd-cf7c-44a1-8f8b-7d4751fee3b2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2250
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: ServiceNow CMDB
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if the ServiceNow CMDB integration instance is configured
        to continue with playbook.
      id: 2c408998-b0a1-4ea0-85cc-1eea917159cc
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Is ServiceNow CMDB enabled?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 2c408998-b0a1-4ea0-85cc-1eea917159cc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 710
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.BypassAddRecord
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines if the ${inputs.BypassAddRecord} input was set to "true"
        in order to bypass the "Add asset to CMDB".
      id: 595fef6d-8bc5-4cd4-8713-bb70d6892ea2
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Was bypass input set to "true"?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 595fef6d-8bc5-4cd4-8713-bb70d6892ea2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1580
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: sys_class_name
                root: ServiceNowCMDB.Record.Attributes
          operator: isEqualString
          right:
            value:
              simple: cmdb_ci_network_adapter
      label: "yes"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the returned CI is a network adapter.
      id: caa5e8dc-a1cf-4bc1-861c-2a8f763f9304
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Is the CI a network adapter?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: caa5e8dc-a1cf-4bc1-861c-2a8f763f9304
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1580
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      class:
        simple: cmdb_ci_network_adapter
      sys_id:
        complex:
          accessor: sys_id
          root: ServiceNowCMDB.Records
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow CMDB
      description: Query attributes and relationship information for a specific record.
      id: 0505c752-d13b-4ee6-851b-f1ee5cd5f2ab
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Get record by ID and Network adapter CI
      playbooktaskmissingcomponent: null
      script: ServiceNow CMDB|||servicenow-cmdb-record-get-by-id
      type: regular
      version: -1
    taskid: 0505c752-d13b-4ee6-851b-f1ee5cd5f2ab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1810
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "14_7_#default#": 0.41,
      "9_7_No": 0.32
    },
    "paper": {
      "dimensions": {
        "height": 2025,
        "width": 1250,
        "x": 450,
        "y": 570
      }
    }
  }
