contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    isoverridable: false
    itemVersion: 3.3.21
    packID: Jira
    packName: Atlassian Jira
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    supportedModules:
    - X1
    - X3
    - X5
    - ENT_PLUS
    - agentix
    - xsiam
    toServerVersion: ""
description: Mirror Jira Ticket is designed to serve as a sub-playbook, which enables
  ticket mirroring with Jira.
id: Mirror Jira Ticket
inputs:
- description: Jira Ticket ID to mirror.
  key: TicketId
  playbookInputQuery: null
  required: false
  value: {}
- description: Set the mirror instance name to enable mirroring with Jira.
  key: MirrorInstanceName
  playbookInputQuery: null
  required: false
  value: {}
- description: "Set the mirror direction to one of the following values: \n1. In\n2.
    Out\n3. Both"
  key: MirrorDirection
  playbookInputQuery: null
  required: false
  value: {}
- description: Set tags for mirror comments and files to Jira
  key: MirrorTags
  playbookInputQuery: null
  required: false
  value: {}
- description: |
    Set the value to true or false to determine if the FieldPolling sub-playbook will be executed in the context of a parent playbook.
    This is useful in cases when it is needed to wait for the Jira issue to be resolved in order to continue the parent playbook.
  key: 'FieldPolling '
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Set interval time for the polling to run
    (In minutes)
  key: FieldPollingInterval
  playbookInputQuery: null
  required: false
  value: {}
- description: |2-

    Set the amount of time to poll the status of the ticket before declaring a timeout and resuming the playbook.
    (In minutes)
  key: FieldPollingTimeout
  playbookInputQuery: null
  required: false
  value: {}
name: Mirror Jira Ticket
outlinetasks: {}
outputs: []
possibleresponses: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b3fb695c-6437-4c1d-8b3f-f6cd1c6eb929
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: b3fb695c-6437-4c1d-8b3f-f6cd1c6eb929
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      dbotMirrorDirection:
        complex:
          root: inputs.MirrorDirection
      dbotMirrorId:
        complex:
          root: inputs.TicketId
      dbotMirrorInstance:
        complex:
          root: inputs.MirrorInstanceName
      dbotMirrorTags:
        complex:
          root: inputs.MirrorTags
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of an alert.
      id: e050eea9-ff4c-4afc-8a65-efcffb1f37e2
      iscommand: true
      istaskmissingcomponenterrordismissed: false
      name: Set Mirroring fields
      playbooktaskmissingcomponent: null
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: e050eea9-ff4c-4afc-8a65-efcffb1f37e2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 550
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f9c6dfc4-2b6f-48c7-832c-b4b0532e6a19
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: f9c6dfc4-2b6f-48c7-832c-b4b0532e6a19
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1140
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: 'inputs.FieldPolling '
                transformers:
                - operator: toLowerCase
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Conditional task to verify if FieldPolliung value = true.
      id: 669cf93d-4f57-4cd5-861d-1013e5f2883b
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Is FieldPolling set to true?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: 669cf93d-4f57-4cd5-861d-1013e5f2883b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 720
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: jirastatus
      frequency:
        complex:
          root: inputs.FieldPollingInterval
      timeout:
        complex:
          root: inputs.FieldPollingTimeout
      value:
        simple: Done
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook polls a field to check if a specific value exists.
      id: fb7fa6c1-2aef-47a8-8621-7d3f9fd0c21e
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Field Polling - Generic
      playbookId: Field Polling - Generic
      playbooktaskmissingcomponent: null
      type: playbook
      version: -1
    taskid: fb7fa6c1-2aef-47a8-8621-7d3f9fd0c21e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 980
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_8_#default#": 0.19
    },
    "paper": {
      "dimensions": {
        "height": 805,
        "width": 380,
        "x": 450,
        "y": 400
      }
    }
  }
