adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    isoverridable: false
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    supportedModules: []
    toServerVersion: ""
description: A playbook to check if VectraXDR integration is enabled, determine if
  the entity is an Account or Host, and add a note.
dirtyInputs: true
id: cdb85928-0ed1-4f38-8218-9bf68e4217dc
inputs: []
name: VectraXDR Entity Verification
outlinetasks: {}
outputs: []
possibleresponses: []
quiet: true
starttaskid: "0"
tags:
- AI Assisted
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e7c4b711-e5b1-424d-8ea0-1b375cbadacd
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: e7c4b711-e5b1-424d-8ea0-1b375cbadacd
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 926e213f-e833-48f8-82f2-d3ac14c7ff34
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 926e213f-e833-48f8-82f2-d3ac14c7ff34
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1050,
          "y": 850
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      "no":
      - "1"
      "yes":
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: VectraXDR
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3133bd4a-d4c7-4c32-8686-7d02c793fafd
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Is VectraXDR Integration Enabled?
      playbooktaskmissingcomponent: null
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 3133bd4a-d4c7-4c32-8686-7d02c793fafd
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
  "3":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: ${incident.entityType}
          operator: isEqualString
          right:
            value:
              simple: Account
        - ignorecase: true
          left:
            iscontext: true
            value:
              simple: ${incident.entity_type}
          operator: isEqualString
          right:
            value:
              simple: Account
      label: Account
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: ${incident.entityType}
          operator: isEqualString
          right:
            value:
              simple: Host
        - ignorecase: true
          left:
            iscontext: true
            value:
              simple: ${incident.entity_type}
          operator: isEqualString
          right:
            value:
              simple: Host
      label: Host
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      Account:
      - "5"
      Host:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: feb54bbd-e18d-49eb-8701-7d61e1e0083e
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Is entity Account or Host?
      playbooktaskmissingcomponent: null
      type: condition
      version: -1
    taskid: feb54bbd-e18d-49eb-8701-7d61e1e0083e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 250,
          "y": 450
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: true
    quietmode: 0
    scriptarguments:
      value:
        simple: 'VectraXDR Integration: Entity is verified to be a Host.'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09fd711d-9b41-4c79-8ea0-64391ed01df4
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Add note for Host
      playbooktaskmissingcomponent:
        connectors: []
        missingcomponentenrichment: []
        packid: ""
        status: not_installed
      script: print
      type: regular
      version: -1
    taskid: 09fd711d-9b41-4c79-8ea0-64391ed01df4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 250,
          "y": 650
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: true
    quietmode: 0
    scriptarguments:
      value:
        simple: 'VectraXDR Integration: Entity is verified to be an Account.'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2a1f1571-edba-435b-8d58-75fb2cc9ad46
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: Add note for Account
      playbooktaskmissingcomponent:
        connectors: []
        missingcomponentenrichment: []
        packid: ""
        status: not_installed
      script: print
      type: regular
      version: -1
    taskid: 2a1f1571-edba-435b-8d58-75fb2cc9ad46
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -150,
          "y": 650
        }
      }
version: -1
