adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    isoverridable: false
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    supportedModules: []
    toServerVersion: ""
id: 0332c318-0c9e-442b-8a66-59ce5ebb8874
inputs: []
name: asasdasd
outlinetasks: {}
outputs: []
possibleresponses: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0c92e9b0-e53f-4828-8b3d-35e19a197aa4
      iscommand: false
      istaskmissingcomponenterrordismissed: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: 0c92e9b0-e53f-4828-8b3d-35e19a197aa4
    timertriggers: []
    type: start
version: -1
