args:
- default: true
  description: The values we should translate.
  name: values
  required: true
  supportedModules: []
- description: The translated values we will use to replace the values.
  name: translated
  required: true
  supportedModules: []
- description: The value to compare and replace.
  name: input
  required: true
  supportedModules: []
comment: 'Map the given values to the translated values. If given values: a,b,c, and
  translated: 1,2,3, then the input will return 1.'
commonfields:
  id: MapValues
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    isoverridable: false
    itemVersion: 1.22.44
    packID: CommonScripts
    packName: Common Scripts
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    supportedModules: []
    toServerVersion: ""
engineinfo: {}
mainengineinfo: {}
name: MapValues
pswd: ""
restrictioncenter: {}
runas: DBotWeakRole
runonce: false
script: |
  // pack version: 1.22.44
  if (typeof args.input === 'object' && args.input !== null) {
      throw 'Input cannot be an object. Please provide a string or a number.';
  }

  var values = argToList(args.values);
  var translated = argToList(args.translated);
  var input = String(args.input).toLowerCase();

  for (var i=0; i<values.length && i<translated.length; i++) {
      if (typeof values[i] === 'object' && values[i] !== null) {
          throw 'Values cannot contain objects. Please provide strings or numbers.';
      }
      if (input === String(values[i]).toLowerCase()) {
          return translated[i];
      }
  }
  return args.input;
scripttarget: 0
signature: DIyt0MAvAaQ0tzBoL44lr1oaOvnJTX1flCbm9f0qdYqr46++mWyzz+3eAq0yrgoBmt4jVNq9RU5llEtELz0bybIhms2xA0gneFfVnO60+FWIMrXvI2RdCVanvmo8GygYS7cv1IwZ5Gm70bFyG3trjQ0F49/TljrcBwtqNqiZAzntApB7z9dznBUohLnuvkSytb6dor9ZkZN7qe69ntb+yNducFuuLRD3AcPpCa9EpkMHev69F7iblLRRhDahWv08EKZbGYn5qDmQ/o89EormWUBbNmTLgxCmKlmBoHlAC1vfjD/zX4aFaSERyA2ho79TENFbwVtklgKUsgBq6+/yaQ==
system: true
tags:
- Utility
type: javascript
