args:
- default: true
  description: First value for comparison
  name: left
  supportedModules: []
- description: Second value for comparison
  name: right
  supportedModules: []
comment: Check whether the values provided in arguments are equal. If either of the
  arguments are missing, no is returned.
commonfields:
  id: AreValuesEqual
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    isoverridable: false
    itemVersion: 1.22.52
    packID: CommonScripts
    packName: Common Scripts
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    supportedModules: []
    toServerVersion: ""
engineinfo: {}
mainengineinfo: {}
name: AreValuesEqual
outputs:
- contextPath: "yes"
  description: if left is equal to right
- contextPath: "no"
  description: if left is not equal to right
pswd: ""
restrictioncenter: {}
runas: DBotWeakRole
runonce: false
script: |
  // pack version: 1.22.52
  if (args.left === undefined || args.right === undefined) {
      return 'no';
  }

  var left = (typeof args.left === 'string') ? args.left : args.left + '';
  var right = (typeof args.right === 'string') ? args.right : args.right + '';
  var answer = 'no';
  if (left === right) {
    answer = 'yes';
  }

  setContext('AreValuesEqual', answer)
  return answer;
scripttarget: 0
signature: EJo41IMe5dJcNVEohBIePTdjsnGyji0id+O4LPpXCJhz4q6wEXBO03vmd7IqUlBWY3AWphy2ZqhQ1o9ZMYY4SqIagbWtci2pTp0q4bpA43lPIo4aq5f7VFflblwuoelTMIL/Xsy+smNlNy1AhKMfVqE8rLkIHs8rtHEaSP1zZlVOQ+LFV8t9TNB22w7LckFLpZ6Evjmlc2Gd8XsHaNOj2qSK5HMIM8IJnzfZYh3ZVN61QICj6H9Vtujxj16fmWFvqOHZ0SqPRvc0MhF4xiPUFUGwjf00HKcSA2lrYNKpiobAvGhVLYOgdBj8eXhverinZ7r2bEX0U41Es6rQhKZjCg==
system: true
tags:
- Utility
- Condition
type: javascript
