args:
- default: true
  description: The values we should translate.
  name: values
  required: true
  supportedModules: []
- description: The translated values we will use to replace the values.
  name: translated
  required: true
  supportedModules: []
- description: The value to compare and replace.
  name: input
  required: true
  supportedModules: []
comment: 'Map the given values to the translated values. If given values: a,b,c, and
  translated: 1,2,3, then the input will return 1.'
commonfields:
  id: MapValues
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    isoverridable: false
    itemVersion: 1.22.39
    packID: CommonScripts
    packName: Common Scripts
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    supportedModules: []
    toServerVersion: ""
engineinfo: {}
mainengineinfo: {}
name: MapValues
pswd: ""
restrictioncenter: {}
runas: DBotWeakRole
runonce: false
script: |
  // pack version: 1.22.39
  if (typeof args.input === 'object' && args.input !== null) {
      throw 'Input cannot be an object. Please provide a string or a number.';
  }

  var values = argToList(args.values);
  var translated = argToList(args.translated);
  var input = String(args.input).toLowerCase();

  for (var i=0; i<values.length && i<translated.length; i++) {
      if (typeof values[i] === 'object' && values[i] !== null) {
          throw 'Values cannot contain objects. Please provide strings or numbers.';
      }
      if (input === String(values[i]).toLowerCase()) {
          return translated[i];
      }
  }
  return args.input;
scripttarget: 0
signature: pWur/v5yGR/483TqUiVHQkEjUrxwR+juoNC7xbHyYBYA9zGQ5rU/1E1bWEN65wZo1hVgzUddXwYaXp/Az+Q1rULczCqVo7UcLuBs1ZcFYyHPcuiMp31i2s8ti00bYHgEAYb77lUk3K7/Q+8Xy7Sa+MN2160MMwBSYsIC5asRTruRR0dA3ngYys+RmQ5q9u6r4DEc6CPXXKBB1lVF8Ngnc5kVLxM7yBwjc+xCiRjiWqod4kwDlTcwtJ75965I2ZvKqMp86oSkjZyXP4p3e15GhigJmiTJIUABg4eqSsL7jLXh8ud8A3nXAOuxSL/bEY0dzS4fROzphGN8ndUttubhDw==
system: true
tags:
- Utility
type: javascript
