args:
- default: true
  description: The parent key to which we append all the other keys.
  name: parent
  required: true
  supportedModules: []
- description: Separated list of keys separated by the specified delimiter (Comma
    is the default delimiter).
  name: keys
  required: true
  supportedModules: []
- description: Separated list of values separated by the specified delimiter (Comma
    is the default delimiter).
  name: values
  required: true
  supportedModules: []
- defaultValue: ','
  description: |-
    Delimiter by which the content of the values and keys lists are separated.
    Eg:  "," , ":", "|||".
  name: delimiter
  supportedModules: []
comment: Set multiple keys/values to the context.
commonfields:
  id: SetMultipleValues
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    isoverridable: false
    itemVersion: 1.22.28
    packID: CommonScripts
    packName: Common Scripts
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    supportedModules: []
    toServerVersion: ""
dockerimage: demisto/python3:3.12.13.10116658
enabled: true
engineinfo: {}
mainengineinfo: {}
name: SetMultipleValues
nativeimage:
- "8.8"
- "8.6"
pswd: ""
restrictioncenter: {}
runas: DBotWeakRole
runonce: false
script: |
  register_module_line('SetMultipleValues', 'start', __line__())
  CONSTANT_PACK_VERSION = '1.22.28'
  demisto.debug('pack id = CommonScripts, pack version = 1.22.28')




  def main():
      delimiter = demisto.args().get("delimiter", ",")
      keys = [k.strip() for k in demisto.args()["keys"].split(delimiter)]
      values_str = demisto.args()["values"]
      if "[" in values_str and "]" in values_str:
          values_str = f"[{values_str}]"
      values = argToList(values_str, separator=delimiter)

      ec = {demisto.args()["parent"] + "(true)": dict(zip(keys, values))}
      demisto.results(
          {
              "Type": entryTypes["note"],
              "Contents": ec,
              "ContentsFormat": formats["json"],
              "HumanReadable": "Keys " + ",".join(keys) + " set",
              "EntryContext": ec,
          }
      )


  if __name__ in ("__main__", "__builtin__", "builtins"):  # pragma: no cover
      main()

  register_module_line('SetMultipleValues', 'end', __line__())
scripttarget: 0
signature: INvJbQ7pO1n6hzNgi9aKZ02RheCJcq746V2iQbUzZ1u/n0suJT5kKoM/AvdNCo7Fj52atLw2uZlAKxC6w+kp5R2ao1r3xp6aK0JGbS6yAUGV59FaZOZ7kPbMZRmWLwsQhKADrJmah+K/YHFNQWzRDXV/4jKpsG8633GGpe6hNRylPWFtjzqMqHCilUwnSsO9uBjeZNsLvJqvjJKbMGMfBQILHX4GfuLI8SkCpQusLbq3G02fioc9Dbn0OLt+wBS1v0CvFf7ZOAaax2y7H7LakE9Fr6XIqunosfCxODZS1t1bV0bINYejp+ZRwGdAqCnvOXNbKfrbzVXttNf0TeYfbg==
subtype: python3
system: true
tags:
- Utility
type: python
