args:
- default: true
  description: First value for comparison
  name: left
  supportedModules: []
- description: Second value for comparison
  name: right
  supportedModules: []
comment: Check whether the values provided in arguments are equal. If either of the
  arguments are missing, no is returned.
commonfields:
  id: AreValuesEqual
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    isoverridable: false
    itemVersion: 1.22.45
    packID: CommonScripts
    packName: Common Scripts
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    supportedModules: []
    toServerVersion: ""
engineinfo: {}
mainengineinfo: {}
name: AreValuesEqual
outputs:
- contextPath: "yes"
  description: if left is equal to right
- contextPath: "no"
  description: if left is not equal to right
pswd: ""
restrictioncenter: {}
runas: DBotWeakRole
runonce: false
script: |
  // pack version: 1.22.45
  if (args.left === undefined || args.right === undefined) {
      return 'no';
  }

  var left = (typeof args.left === 'string') ? args.left : args.left + '';
  var right = (typeof args.right === 'string') ? args.right : args.right + '';
  var answer = 'no';
  if (left === right) {
    answer = 'yes';
  }

  setContext('AreValuesEqual', answer)
  return answer;
scripttarget: 0
signature: ihXh6btN3YN/a578/LPYYfaxnx6o6pWt1EXWwqGHaK8cJWzRMCi8cYG4Zby2QmFJ/nZWpxYBzwMtd8wToaWgvp6u1XovhaV0u++1lkVLIzMufMs5haNzu321/mHqHbqavtI0P/HEw2AcBjp/uCZrfCKx3pz/HJKjV1OzyxQ4zNw7Zd7Y3p51Y6wNq8IH+AcKZYfynO+Jq3pdWHiovxhA32Wra1Z1aouWRZyYSRrnPIfwt3hX/oqsXE+aHfB+As4OMCU8ieiTE8B9dC5BEDqq7bm1UXcoy2tnsB7YJriTNOBtG+rZLtM+I3g/0fk81iEY6Y10+NXzOZtqx3bUQZsh5A==
system: true
tags:
- Utility
- Condition
type: javascript
